
---
title: "Association Rules - ECLAT"
author: "BBDS"
date: "12/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#######################################################################################################
### Free memory Functions
#######################################################################################################

```{r}
# Clear environment
rm(list = ls()) 

# Clear packSalarys
# pacman::p_unload(rgl)

# Clear plots
# dev.off()  # But only if there IS a plot

# Clear console
cat("\014")  # ctrl+L

```


#######################################################################################################
### Working Directory
#######################################################################################################

```{r}
# Set your working directory to save an R file: 
# setwd("/Users/YourName/Desktop") 
# OR Session < Top Level Menu Item >  Set Working Directory
# getwd()
# setwd("G:/NAFIS DS Course/DS - Batch 2/DS - Week 3 -  Data Understanding & Preparation/Session 3.2 - EDA With R/2-  Codes")
```




#######################################################################################################
### Loading Data to RStudio
######################################################################################################## 


# Trans = read.csv('Salary_Data.csv')
```{r}
Trans= read.csv(file.choose(), header = FALSE)# Locate data file, summarize, attach


str(Trans) # structure

names(Trans) # variable names
attributes(Trans)
attributes(Trans)[1]

dim (Trans) # dimensions

nrow(Trans) # number of observations
dim (Trans)[1]

ncol(Trans) # number of variables

summary(Trans)
```



#######################################################################################################
### Find Duplicate records 
#######################################################################################################

```{r}
duplicated(Trans)
anyDuplicated(Trans)
anyDuplicated(Trans, fromLast = TRUE)
```





#######################################################################################################
## Data Preprocessing
#######################################################################################################

```{r}
# install.packages('arules')

library(arules)

read.transactions(file.choose())
```



```{r}
Trans = read.transactions(file.choose(), sep = ',', rm.duplicates = TRUE)

summary(Trans)
```

```{r}
#itemFrequencyPlot()

itemFrequencyPlot(Trans2, topN = 10)
```




#######################################################################################################
## Training Eclat on the Trans
#######################################################################################################
# How to calculate the support - Consider  products that are bought at least 4 times a days

```{r}
4*7/7500
```

# Confidence - We start with default which is 

```{r}
#eclat()
setOfItems = eclat(data = Trans, parameter = list(support = 0.004, minlen = 2))
```



#######################################################################################################
## Visualising the results
#######################################################################################################

```{r}
inspect(sort(setOfItems, by = 'support')[1:10]) # diffirent set of items most frequently purchased together
```










